remove unneeded babelrc dependency
Was just doing some testing concerning failing tests, only to
realize the branch of Istanbul I was using was quite stale...
and forgot to remove this package after testing.

I found a fork of the latest version with alleged fixes for the
error: `TypeError: Cannot read property 'text' of undefined`